# Generated by Django 4.2 on 2023-04-09 19:05

import app_book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('ISBN', models.CharField(max_length=10, validators=[app_book.models.validate_ISBN])),
                ('pages', models.IntegerField(blank=True, default=100)),
                ('languages', models.CharField(choices=[('EN', 'Ingles'), ('ES', 'Espanol'), ('DE', 'Aleman'), ('OT', 'Otro')], default='ES', max_length=2)),
                ('release_date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('publishing_version', models.CharField(choices=[('1ST', 'First'), ('2ND', 'Second'), ('3RD', 'Thid'), ('OTH', 'Other')], default='1ST', max_length=3)),
                ('price', models.IntegerField(default=None, null=True)),
                ('currency', models.CharField(choices=[('US', 'Dolares'), ('PS', 'Pesos Argentinos'), ('EU', 'Euros')], default='PS', max_length=2)),
                ('author_id', models.ManyToManyField(related_name='app_author', to='app_author.author')),
            ],
        ),
    ]
