# Generated by Django 4.2 on 2023-04-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_company', models.IntegerField(choices=[('1', 'Alición Editora'), ('2', 'Ampersand Editorial'), ('3', 'Asunto Impreso Ediciones'), ('4', 'Atlántida Editorial'), ('5', 'Ayarmanot Ediciones'), ('6', 'Corregidor Ediciones'), ('7', 'De Mente Ediciones'), ('8', 'Dunken Editorial'), ('9', 'Ediciones Inta'), ('10', 'Ediciones Novedades Educativas'), ('11', 'Editorial de la Universidad Nacional de Quilmes'), ('12', 'Editorial el Hilo de Ariadna'), ('13', 'Editorial Losada'), ('14', 'Editorial Mansalva'), ('15', 'Editorial Universidad de Buenos Aires'), ('16', 'Eloísa Cartonera'), ('17', 'Emecé Editores'), ('18', 'Libros del Zorzal'), ('19', 'Perfil Editorial'), ('20', 'Otra Editorial')], default='20')),
            ],
        ),
    ]
