# Generated by Django 4.2 on 2023-04-09 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('editorial_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='app_core.editorial')),
                ('author_id', models.IntegerField(primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=100)),
                ('last_names', models.CharField(max_length=100)),
            ],
            bases=('app_core.editorial',),
        ),
    ]
