# Generated by Django 4.2 on 2023-04-09 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('payment_method', models.CharField(choices=[('MP', 'Mercado Pago'), ('CH', 'Efectivo'), ('DB', 'Tarjeta de debito'), ('CC', 'Tarjeta de credito'), ('TF', 'Transferencia bancaria')], default='CH', max_length=2)),
                ('warehouse_id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('delivery', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('amount', models.IntegerField(default=10)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_book', to='app_book.book')),
                ('warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='app_warehouse', to='app_warehouse.warehouse')),
            ],
        ),
    ]
